workflows:
  ios-release:
    name: Diek App - iOS Release Workflow
    max_build_duration: 120
    instance_type: mac_mini_m1
    environment:
      flutter: stable
      xcode: latest
      cocoapods: default
    scripts:
      - name: Initialize platform files
        script: |
          if [ ! -d "ios" ]; then
            flutter create . --platforms=ios,android --org com.sistemasdiek
          fi
      - name: Fetch Flutter dependencies
        script: |
          flutter packages pub get
      - name: Install CocoaPods dependencies
        script: |
          cd ios && pod install
      - name: Disable Xcode mandatory code signing check
        script: |
          xcode-project disable-code-signing --project ios/Runner.xcodeproj || true
      - name: Build Full iOS Release App
        script: |
          flutter build ios --release --no-codesign
          mkdir -p build/ios/ipa/Payload
          cp -r build/ios/iphoneos/Runner.app build/ios/ipa/Payload/
          cd build/ios/ipa
          zip -r DiekApp-Full-Release.ipa Payload
    artifacts:
      - build/ios/iphoneos/*.app
      - build/ios/ipa/*.ipa
      - /tmp/xcodebuild_logs/*.log

  android-release:
    name: Diek App - Android Release Workflow
    max_build_duration: 60
    instance_type: mac_mini_m1
    environment:
      flutter: stable
    scripts:
      - name: Initialize platform files
        script: |
          if [ ! -d "android" ]; then
            flutter create . --platforms=ios,android --org com.sistemasdiek
          fi
      - name: Fetch Flutter dependencies
        script: |
          flutter packages pub get
      - name: Build Android APK
        script: |
          flutter build apk --release
      - name: Build Android App Bundle (.aab)
        script: |
          flutter build appbundle --release
    artifacts:
      - build/app/outputs/flutter-apk/*.apk
      - build/app/outputs/bundle/release/*.aab
