workflows:
  ios-release:
    name: Diek App - iOS Release Workflow
    max_build_duration: 120
    instance_type: mac_mini_m1
    environment:
      flutter: stable
      xcode: latest
      cocoapods: default
      groups:
        - apple_credentials # Configured in Codemagic UI if using Apple Developer Account
      ios_signing:
        distribution_type: ad_hoc
        bundle_identifier: com.sistemasdiek.diekapp
    scripts:
      - name: Initialize platform files
        script: |
          flutter create . --platforms=ios,android --org com.sistemasdiek
      - name: Fetch Flutter dependencies
        script: |
          flutter packages pub get
      - name: Set up iOS signing profiles
        script: |
          xcode-project use-profiles || echo "No code signing profiles found, building unsigned package"
      - name: Build iOS Application
        script: |
          flutter build ios --release --no-codesign
    artifacts:
      - build/ios/iphoneos/Runner.app
      - build/ios/ipa/*.ipa
      - /tmp/xcodebuild_logs/*.log

  android-release:
    name: Diek App - Android Release Workflow
    max_build_duration: 60
    instance_type: mac_mini_m1
    environment:
      flutter: stable
    scripts:
      - name: Initialize platform files
        script: |
          flutter create . --platforms=ios,android --org com.sistemasdiek
      - name: Fetch Flutter dependencies
        script: |
          flutter packages pub get
      - name: Build Android APK
        script: |
          flutter build apk --release
      - name: Build Android App Bundle (.aab)
        script: |
          flutter build appbundle --release
    artifacts:
      - build/app/outputs/flutter-apk/*.apk
      - build/app/outputs/bundle/release/*.aab
